# Generated by Django 3.1 on 2020-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200910_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='Search',
            new_name='search',
        ),
        migrations.AlterField(
            model_name='search',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
